### ISSUE TITLE
Version without special is greater?

### ISSUE THREAD

**Issue by szepeviktor** [cloudflare/semver_bash#8]
`semverGT "2.2.2" "2.2.2-1"` returns OK.

I think 2.2.2-1 comes after 2.2.2.

**Comment by szepeviktor** [comment]
In `semverLT()` it says
```bash
if [[ "_$SPECIAL_A"  != "_" ]] && [[ "_$SPECIAL_B"  == "_" ]] ; then
```
If the *should-be-less* version is not empty and the *should-be-greater* version is empty then it is less.
So the non-empty is less than the empty one. Is it OK?

**Comment by dozoisch** [comment]
Yes. The 4th parameter is mainly for release candidates and stuff like that.

Let's you have

```
2.2.0-rc1
2..2.0-rc2
2.2.0
```

Which one comes first?

Well obviously the two release candidates, and once it's done. `2.2.0` is shipped officially.

This is why the "empty" is greater.

**Comment by szepeviktor** [comment]
Oh! Thank you.
